### PR TITLE
Fixing Glottocodes and CLDF conversion

### PR DESCRIPTION
**Pull request by CMUgarte**
@chrzyki, here is the PR for the wrong Glottocodes. I didn't quite get the note on the `requirements.txt` file. How can I fix the `etc/languages.tsv`file and run the `CLDF conversion` without having the dataset in my local environment?

### CODE REVIEW

**Comment by chrzyki** [comment]
If you have a dedicated ('clean') environment for building, e.g.:

```
$ python -m venv venv
$ source venv/bin/activate
$ pip install cldfbench pylexibank
```

And then do a

```
$ cldfbench lexibank.makecldf lexibank_dataset.py --glottolog-version [...]
```

the dataset doesn't need to be installed to be built.

**Comment by chrzyki** [comment]
And thank you for updating the dataset, I'll check momentarily. Thank you as well for preparing the PR. :)

**Comment by CMUgarte** [comment]
> If you have a dedicated ('clean') environment for building, e.g.:
> 
> ```
> $ python -m venv venv
> $ source venv/bin/activate
> $ pip install cldfbench pylexibank
> ```
> 
> And then do a
> 
> ```
> $ cldfbench lexibank.makecldf lexibank_dataset.py --glottolog-version [...]
> ```
> 
> the dataset doesn't need to be installed to be built.

This is my normal workflow after cloning the repo.

**Comment by chrzyki** [comment]
> > If you have a dedicated ('clean') environment for building, e.g.:
> > ```
> > $ python -m venv venv
> > $ source venv/bin/activate
> > $ pip install cldfbench pylexibank
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then do a
> > ```
> > $ cldfbench lexibank.makecldf lexibank_dataset.py --glottolog-version [...]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the dataset doesn't need to be installed to be built.
> 
> This is my normal workflow after cloning the repo.

And here everything is all well! In the other PR I suppose there has been at some point a `$ pip install -e .` or similar in the dataset directory which is why it was installed as a Python package in the build environment.

**Review by chrzyki — APPROVED** [review]

**Comment by CMUgarte** [comment]
> > > If you have a dedicated ('clean') environment for building, e.g.:
> > > ```
> > > $ python -m venv venv
> > > $ source venv/bin/activate
> > > $ pip install cldfbench pylexibank
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And then do a
> > > ```
> > > $ cldfbench lexibank.makecldf lexibank_dataset.py --glottolog-version [...]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the dataset doesn't need to be installed to be built.
> > 
> > 
> > This is my normal workflow after cloning the repo.
> 
> And here everything is all well! In the other PR I suppose there has been at some point a `$ pip install -e .` or similar in the dataset which is why it was installed as a Python package in the build environment.

Oh, I see! Yes, I also `$ pip install -e .` for the other venv. I'll directly install `pylexibank` after creating the fresh venv as the standard workflow for this :) thanks for the info!

**Comment by chrzyki** [comment]
> > > > If you have a dedicated ('clean') environment for building, e.g.:
> > > > ```
> > > > $ python -m venv venv
> > > > $ source venv/bin/activate
> > > > $ pip install cldfbench pylexibank
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > And then do a
> > > > ```
> > > > $ cldfbench lexibank.makecldf lexibank_dataset.py --glottolog-version [...]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > the dataset doesn't need to be installed to be built.
> > > 
> > > 
> > > This is my normal workflow after cloning the repo.
> > 
> > 
> > And here everything is all well! In the other PR I suppose there has been at some point a `$ pip install -e .` or similar in the dataset which is why it was installed as a Python package in the build environment.
> 
> Oh, I see! Yes, I also `$ pip install -e .` for the other venv. I'll directly install `pylexibank` after creating the fresh venv as the standard workflow for this :) thanks for the info!

Sounds good! This is also a good way to catch unspecified dependencies for a dataset, e.g. if a dataset requires more than the typical libraries. If building fails with failed imports this usually means there are other dependencies for the dataset that can then be added successively to the local env and thus be captured properly in the requirements.

**Comment by CMUgarte** [comment]
> > > > > If you have a dedicated ('clean') environment for building, e.g.:
> > > > > ```
> > > > > $ python -m venv venv
> > > > > $ source venv/bin/activate
> > > > > $ pip install cldfbench pylexibank
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > And then do a
> > > > > ```
> > > > > $ cldfbench lexibank.makecldf lexibank_dataset.py --glottolog-version [...]
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > the dataset doesn't need to be installed to be built.
> > > > 
> > > > 
> > > > This is my normal workflow after cloning the repo.
> > > 
> > > 
> > > And here everything is all well! In the other PR I suppose there has been at some point a `$ pip install -e .` or similar in the dataset which is why it was installed as a Python package in the build environment.
> > 
> > 
> > Oh, I see! Yes, I also `$ pip install -e .` for the other venv. I'll directly install `pylexibank` after creating the fresh venv as the standard workflow for this :) thanks for the info!
> 
> Sounds good! This is also a good way to catch unspecified dependencies for a dataset, e.g. if a dataset requires more than the typical libraries. If building fails with failed imports this usually means there are other dependencies for the dataset that can then be added successively to the local env and thus be captured properly in the requirements.

Wow, amazing. It is clear to me the advantages (each time more) of working individually for each dataset and with a fresh venv. Thanks for the thorough clarification as always, @chrzyki :)

**Comment by CMUgarte** [comment]
@chrzyki, we can merge this PR :)

**Review by chrzyki — APPROVED** [review]

**Pull request merged**
